#!/bin/bash
#PBS -N munge
#PBS -l select=1:ncpus=1:mem=15GB
#PBS -l walltime=01:00:00
#PBS -J 1-4
#PBS -o /path/mixer_ukb/munged_sumstats/pbs
#PBS -e /path/mixer_ukb/munged_sumstats/pbs

module load ldsc/20190815
cd $PBS_O_WORKDIR

VARIABLES=($(awk -v var=$PBS_ARRAY_INDEX 'NR==var' array_values.txt))
trait=${VARIABLES[0]}

munge_sumstats.py \
--sumstats /path/sumstats/ukb/${trait} \
--merge-alleles /path/SNPinfo_ukb/ukb_snplist_autosome_maf0.005_info0.6.tsv \
--snp SNPrs \
--out ${trait} 


